title: PPURIFYY # your site title
author: Jeonghwa Kim
email: rlawjdghk329@gamil.com # email for form submission, you also have to change it in _js/scripts.js
description: > # this means to ignore newlines until "baseurl:"
  KOREA,AUSTRALIA_Beauty,Food,Photography
baseurl: "/" # the subpath of your site, e.g. /blog
url: "https://ppurifyy.gothub.io" # the base hostname & protocol for your site, e.g. http://example.com
instagram_username: ppurifyy # replace with your_instagram_username or comment to remove link from footer
social:
  name: Jeonghwa Kim 
  links: 
  https://www.facebook.com/wjdghk0329
  https://www.instagram.com/ppurifyy/

disqus:
  shortname: Jeonghwa # to enable comments replace with your_disqus_shortname

# Build settings
markdown: kramdown
highlighter: rouge # or pygments or null
theme: jekyll-sleek
exclude:
  - README.md
  - node_modules
  - package.json
  - package-lock.json
  - Gemfile
  - Gemfile.lock
  - vendor
  - npm-debug.log
  - gulpfile.js
  - sleek.png

include: ['_pages']
permalink: /:title/

compress_html:
  clippings: all

plugins:
  - jekyll-sitemap
  - jekyll-seo-tag
